from sli_ui_toolkit.ui.widgets.atomic import (
    ButtonPainter,
    CheckBox,
    ComboBox,
    CustomGroupBuilder,
    CustomGroupWidget,
    CustomLineEdit,
    DropZoneLabel,
    Label,
    LabelConfig,
    LabelVariantSpec,
    LoadingSpinner,
    InstancesCounterButton,
    MinimalistScrollBar,
    OverlayScrollArea,
    RadioButton,
    ScrollableComboBox,
    Slider,
    SpinBox,
    Switch,
    TimeLineEdit,
    get_label_variant,
    register_label_variant,
)
from sli_ui_toolkit.ui.widgets.buttons import (
    Button,
    ButtonConfig,
    ButtonGroup,
    ButtonRegion,
    ButtonSpec,
    BehaviorSpec,
    ClickBehavior,
    ContentSpec,
    CustomSplit,
    Divider,
    GridSplit,
    HorizontalSplit,
    LongPressBehavior,
    MenuBehavior,
    RegionSpec,
    RegionStyle,
    ScrollBehavior,
    ShapeSpec,
    SingleRegionSplit,
    ToggleBehavior,
    VerticalSplit,
)
from sli_ui_toolkit.ui.widgets.composite import (
    BaseFlyout,
    DragGhostWidget,
    IconAction,
    IconActionFlyout,
    IconListItem,
    IconListWidget,
    IndexedToggleFlyout,
    ColorSwatch,
    MarkdownHelpDialog,
    MarkdownHelpSection,
    LogConsoleEntry,
    LogConsoleWidget,
    ProcessConsoleWidget,
    ScrollableDialogPage,
    SidebarDialogShell,
    SimpleOptionsFlyout,
    CalendarDayButton,
    CalendarDayInfo,
    CalendarMonthInfo,
    CalendarViewModel,
    CalendarWidget,
    CalendarYearInfo,
    SunburstChartWidget,
    SunburstSegmentData,
    SunburstSegmentItem,
    TimelineCallbacks,
    TimelineWidget,
    ToastAction,
    ToastManager,
    ToastNotification,
    UnifiedFlyout,
    UnifiedFlyoutItem,
    SimpleUnifiedFlyoutStore,
    SimpleUnifiedFlyoutController,
)
from sli_ui_toolkit.ui.widgets.atomic.tooltips import (
    application_tooltips_enabled,
    install_application_tooltips,
    set_application_tooltips_enabled,
)
from sli_ui_toolkit.ui.widgets.helpers import (
    UnderlineConfig,
    apply_editable_text_behavior,
    calculate_centered_overlay_geometry,
    draw_bottom_underline,
    draw_rounded_shadow,
)
from sli_ui_toolkit.ui.widgets.overlays import (
    DragDropOverlay,
    OverlayItem,
    OverlaySlot,
    TopLevelInWindowOverlay,
)
from sli_ui_toolkit.style import (
    WidgetStyleTokens,
    read_widget_style,
    update_widget_style,
)

import warnings

_LEGACY_BUTTON_EXPORTS = {
    "IconButton",
    "SimpleIconButton",
    "ToggleIconButton",
    "ScrollableIconButton",
    "ToggleScrollableIconButton",
    "LongPressIconButton",
    "NumberedToggleIconButton",
    "UnifiedIconButton",
    "AutoRepeatButton",
    "CustomButton",
    "ToolButton",
    "ToolButtonWithMenu",
    "MagnifierInstancesButton",
}

_LEGACY_BUTTON_GROUP_EXPORTS = {
    "ButtonGroupContainer",
}

_LEGACY_BUTTON_SENTINEL_EXPORTS = {
    "ButtonType",
    "ButtonMode",
}

__all__ = [
    "Button",
    "ButtonConfig",
    "ButtonGroup",
    "ButtonRegion",
    "ButtonSpec",
    "BehaviorSpec",
    "ClickBehavior",
    "ContentSpec",
    "CustomSplit",
    "Divider",
    "GridSplit",
    "HorizontalSplit",
    "LongPressBehavior",
    "MenuBehavior",
    "RegionSpec",
    "RegionStyle",
    "ScrollBehavior",
    "ShapeSpec",
    "SingleRegionSplit",
    "ToggleBehavior",
    "VerticalSplit",
    "ButtonPainter",
    "BaseFlyout",
    "CustomGroupBuilder",
    "CustomGroupWidget",
    "CustomLineEdit",
    "DropZoneLabel",
    "CheckBox",
    "ComboBox",
    "RadioButton",
    "Slider",
    "SpinBox",
    "Switch",
    "Label",
    "LabelConfig",
    "LabelVariantSpec",
    "DragGhostWidget",
    "IconAction",
    "IconActionFlyout",
    "IconListItem",
    "IconListWidget",
    "IndexedToggleFlyout",
    "MarkdownHelpDialog",
    "MarkdownHelpSection",
    "LoadingSpinner",
    "LogConsoleEntry",
    "LogConsoleWidget",
    "InstancesCounterButton",
    "ProcessConsoleWidget",
    "ColorSwatch",
    "MinimalistScrollBar",
    "OverlayScrollArea",
    "ScrollableComboBox",
    "ScrollableDialogPage",
    "SimpleOptionsFlyout",
    "SidebarDialogShell",
    "TimeLineEdit",
    "get_label_variant",
    "register_label_variant",
    "CalendarDayButton",
    "CalendarDayInfo",
    "CalendarMonthInfo",
    "CalendarViewModel",
    "CalendarWidget",
    "CalendarYearInfo",
    "SunburstChartWidget",
    "SunburstSegmentData",
    "SunburstSegmentItem",
    "TimelineCallbacks",
    "TimelineWidget",
    "ToastAction",
    "ToastManager",
    "ToastNotification",
    "UnifiedFlyout",
    "UnifiedFlyoutItem",
    "SimpleUnifiedFlyoutStore",
    "SimpleUnifiedFlyoutController",
    "application_tooltips_enabled",
    "install_application_tooltips",
    "set_application_tooltips_enabled",
    "UnderlineConfig",
    "apply_editable_text_behavior",
    "calculate_centered_overlay_geometry",
    "draw_bottom_underline",
    "draw_rounded_shadow",
    "DragDropOverlay",
    "OverlayItem",
    "OverlaySlot",
    "TopLevelInWindowOverlay",
    "WidgetStyleTokens",
    "read_widget_style",
    "update_widget_style",
]


def __getattr__(name: str):
    if name in _LEGACY_BUTTON_EXPORTS:
        warnings.warn(
            f"{name} is deprecated and will be removed in 0.3.0. "
            "Use Button from sli_ui_toolkit.widgets instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return Button
    if name in _LEGACY_BUTTON_GROUP_EXPORTS:
        warnings.warn(
            f"{name} is deprecated and will be removed in 0.3.0. "
            "Use ButtonGroup from sli_ui_toolkit.widgets instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return ButtonGroup
    if name in _LEGACY_BUTTON_SENTINEL_EXPORTS:
        warnings.warn(
            f"{name} is deprecated and will be removed in 0.3.0. "
            "Use Button keyword arguments or ButtonSpec instead.",
            DeprecationWarning,
            stacklevel=2,
        )
        return Button
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
